### ISSUE TITLE
Whatever this is

### ISSUE THREAD

**Issue by ramannoodl3s** [giantninja908/JANREX#10]
Playing pubs on skytemple, closed out mid game, got this on the exit. No clue what it means lmao 
![image](https://user-images.githubusercontent.com/87043389/125205779-cb318c00-e238-11eb-96c2-d8608c6aa29e.png)

**Comment by giantninja908** [comment]
The issue is it tries to close a pop up window that already got closed, I could probably fix it soon

**Comment by giantninja908** [comment]
Did 7242e1c fix it?
