### ISSUE TITLE
"esc" Issue

### ISSUE THREAD

**Issue by MmmGor** [giantninja908/JANREX#11]
"esc" key not working when moving from in game to menu.

**Comment by TheUltimateKeval** [comment]
Can you provide more information like your platform and DevTools console logs? (Press `Ctrl + Shift + I` to open DevTools)

**Comment by MmmGor** [comment]
![image](https://user-images.githubusercontent.com/87295931/125238993-e33af700-e29c-11eb-8006-f8627776db21.png)

**Comment by TheUltimateKeval** [comment]
The script which handles the `Esc` keybind is not loading because you haven't created the `src/scripts/menu-timer.js` file after requiring it in `src/preload.js`.

Either put the `menu-timer.js` file or remove `require("./scripts/menu-timer")` from `preload.js`.

**Comment by MmmGor** [comment]
No but the thing is I already have it there, also looking at the logs do you see anything that could be messing up all my other scripts because I lost lobby swapping and black sky after adding those in ;-;

![image](https://user-images.githubusercontent.com/87295931/125241722-a7a22c00-e2a0-11eb-9cd3-d7e754f8bc7d.png)

**Comment by TheUltimateKeval** [comment]
> No but the thing is I already have it there, also looking at the logs do you see anything that could be messing up all my other scripts because I lost lobby swapping and black sky after adding those in ;-;

Did you run `yarn package-win` after adding the script?

**Comment by giantninja908** [comment]
> No but the thing is I already have it there, also looking at the logs do you see anything that could be messing up all my other scripts because I lost lobby swapping and black sky after adding those in ;-;
> 
> ![image](https://user-images.githubusercontent.com/87295931/125241722-a7a22c00-e2a0-11eb-9cd3-d7e754f8bc7d.png)

This looks like it’s named menu-timer.js.js
