### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by SleevanPJ** [giantninja908/JANREX#17]
When I go into a custom game, like a parkour map, it first of all brings me into a new tab, which is unnecessary, and it says "We are discontiuiing this version of the Krunker Client as we are preparing for the steam release. If you want to update your client to the latest version. Please download and install the new client". Then when I exit out of the alert, I dont see my css used in-game, where is my css?

**Comment by TheUltimateKeval** [comment]
Since it is showing the client popup, it means it is not loading the preload script. Can you send a screenshot of DevTools Console? (Press `Ctrl + Shift + I` to open DevTools)
