### ISSUE TITLE
Map hosting and testing not working as intended

### ISSUE THREAD

**Issue by ramannoodl3s** [giantninja908/JANREX#3]
When in the editor and pressing test map / host map buttons, a new window does not open as it should. However, if you restart the client it loads you into the hosted map lobby, i.e. Krunker sandbox, without the editor or main game.

**Comment by giantninja908** [comment]
Can you please confirm that 7415b8e fixes this issue?

**Comment by giantninja908** [comment]
correction: 764ad41

**Comment by giantninja908** [comment]
Lack of response, closing the issue
